### ISSUE TITLE
psalm fails because of missing config file

### ISSUE THREAD

**Issue by kaystrobach** [EdgedesignCZ/phpqa#118]
Thanks a lot for phpqa!

Sadly i found an problem with the integration of **psalm**.

#steps to reproduce:

## Installation
```
    - composer global require edgedesign/phpqa --update-no-dev
    - composer global require jakub-onderka/php-parallel-lint jakub-onderka/php-console-highlighter phpstan/phpstan vimeo/psalm friendsofphp/php-cs-fixer
    - mkdir -p public/phpqa
    - PATH="$PATH:$HOME/.composer/vendor/bin/"
    - phpqa --report --analyzedDirs Packages/Application/PackageName --buildDir public/phpqa --tools phploc,phpcpd,phpcs,pdepend,phpmd,phpmetrics,php-cs-fixer,parallel-lint,phpstan,psalm
```
## .phpqa.yml

```
phpcs:
    standard: PSR2
    # number of allowed errors is compared with warnings+errors, or just errors from checkstyle.xml
    ignoreWarnings: false
    # https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting
    reports:
        cli:
            - full
        #file:
            # checkstyle is always included and overriden
            # checkstyle: checkstyle.xml
            # you can include custom reports (https://github.com/wikidi/codesniffer/blob/master/reports/wikidi/Summary.php#L39)
            # ./vendor/owner/package/src/MySummaryReport.php: phpcs-summary.html

php-cs-fixer:
    # http://cs.sensiolabs.org/#usage
    rules: '@PSR2'
    allowRiskyRules: false
    # by default the tool is runned in dry-run mode (no fixers are applied)
    isDryRun: true

phpstan:
    level: 0

phpunit:
    # binary: vendor/bin/phpunit
    binary: bin/phpunit
    # phpunit.xml
    config: Build/BuildEssentials/PhpUnit/UnitTests.xml
    reports:
        file: []
            # log: [junit, tap, json]
            # testdox: [html, text]
            # coverage: [html, clover, crap4j, php, text, xml] # requires XDebug extension

psalm:
    config: .psalm.xml
    deadCode: true
    threads: 5
    showInfo: true

# Php file extensions to parse.
extensions:
    - php
```

## Result

The result is an exit code larger than zero.

Additionally there is an output in the `phpqa.html#psalm` which is: `DOMDocument::load(): I/O warning : failed to load external entity "/builds/projects/public/phpqa/psalm.xml"`.

The `phpqa/pslam.xml` does not exist, **BUT** there is an `psalm-phpqa.xml`

Maybe you can either point me to the correct config or accept that as an bug.
