### ISSUE TITLE
.phpqa.yml set multi extensions phpmetrics analyize will got No file found LogicException

### ISSUE THREAD

**Issue by mouson** [EdgedesignCZ/phpqa#187]
.phpqa.yml

```yml
phpqa:
  tools:
    - phpmetrics
  extensions:
    - php
    - inc
```

```
[Edge\QA\Task\ParallelExec] "/phpqa/vendor/bin/phpmetrics" "./"  --excluded-dirs="Reports|vendor" --extensions php,inc --offline --report-html "PHPQA/phpmetrics.html" --report-xml "PHPQA/phpmetrics.xml"
```

![image](https://user-images.githubusercontent.com/858588/67829195-4a3c6a80-fb11-11e9-8faa-357daa129f5c.png)

`--extensions php,inc` change to `--extensions "php|inc"` can fix this problem.
