### ISSUE TITLE
Unsupported operand types (phpstan, php 7.1)

### ISSUE THREAD

**Issue by andrewprofile** [EdgedesignCZ/phpqa#201]
When I use PHP 7.1 and I have defined the phpstan.neon file in the main project directory I get an error
> PHP Notice:  Undefined index: parameters in /vendor/edgedesign/phpqa/src/Tools/Analyzer/Phpstan.php on line 33
PHP Fatal error:  Uncaught Error: Unsupported operand types in /vendor/edgedesign/phpqa/src/Tools/Analyzer/Phpstan.php:33

https://github.com/EdgedesignCZ/phpqa/blob/master/src/Tools/Analyzer/Phpstan.php#L36

**Comment by zdenekdrahos** [comment]
I don't think it's an issue caused by phpqa. You probably don't have `parameters` array:

* `Phpstan.php on line 33`, so you are probably using [v1.2.3](https://github.com/EdgedesignCZ/phpqa/blob/v1.23.3/src/Tools/Analyzer/Phpstan.php#L33)
* I can reproduce it by adding `parameters: null` to `phpstan.neon`

![image](https://user-images.githubusercontent.com/7994022/106463961-52175700-6498-11eb-94d3-0707bbac376e.png)

**Comment by andrewprofile** [comment]
Thanks for analyzing the problem, but here is my `phpstan.neon` file
```
includes:
    - %currentWorkingDirectory%/vendor/phpstan/phpstan-phpunit/extension.neon
    - %currentWorkingDirectory%/vendor/phpstan/phpstan-phpunit/rules.neon
rules:
    - Ergebnis\PHPStan\Rules\Expressions\NoEvalRule
parameters:
    bootstrap: %currentWorkingDirectory%/vendor/autoload.php
    autoload_files:
        - %currentWorkingDirectory%/tests/bootstrap.php
```
As you can see, I have a `parameters` array.
