### ISSUE TITLE
Phpstan neon generation is incorrect

### ISSUE THREAD

**Issue by archfz** [EdgedesignCZ/phpqa#228]
Phpstan neon ignoredErrors message regesx are double escaped:
```neon
    ignoreErrors:
    	-
    		message: '#Call to an undefined method Codeception\\.+#'
    		path: %currentWorkingDirectory%/tests/
```
becomes
```neon
    ignoreErrors:
    	-
    		message: '#Call to an undefined method Codeception\\\\.+#'
    		path: %currentWorkingDirectory%/tests/
```

**Comment by zdenekdrahos** [comment]
That's how [Neon::encode](https://github.com/EdgedesignCZ/phpqa/blob/v1.24.0/src/Tools/Analyzer/Phpstan.php#L53) works. I've tried ignoring a simple message and an advanced message. Errors are correctly excluded even if `phpstan-phpqa.neon` contains double escaped slashes.

```yml
ignoreErrors:
    - '#Call to an undefined static method Symfony\\Component\\Process\\Process::fromShellCommandline\(\)\.#'
    - message: '#Call to an undefined static method Symfony\\Component\\Process\\Process::fromShellCommandline\(\)\.#'
      path: %currentWorkingDirectory%/src/Tools/GetVersions.php
```

Please reopen, if there is a bug in phpqa.
