### ISSUE TITLE
Custom binary location is relative to phpqa.yml

### ISSUE THREAD

**Issue by LeeShan87** [EdgedesignCZ/phpqa#252]
I've tried to run phpqa with phive installed PHPUnit in a Docker container.
My setup looks like:
Phpqa and phive installed at /phpqa folder.
I mount the application to /application folder.

```
phpqa:
   tools:
      - phpunit
phpunit:
    binary: ../phpqa/tools/phpunit
    config: phpunit.xml
    reports:
        file: 
            coverage: [html, clover, crap4j, xml]
tool:
    phpunit: Edge\QA\Tools\Analyzer\Phpunit
```
If I tried to run phpunit with absolute path to the binary the tool was not found.
I've added a var_dump before https://github.com/EdgedesignCZ/phpqa/blob/master/src/Config.php#L80
And found out it became: ```string(33) "/application//phpqa/tools/phpunit"```

Just a note if someone has a similar issue using custom phar binaries.
Keep up the good work. I really love your tool. :)
