### ISSUE TITLE
phpmetrics specific config file

### ISSUE THREAD

**Issue by cbastienbaron** [EdgedesignCZ/phpqa#74]
Hi guys,

This is possible to provide a specific `.phpmetrics.yml` config via `.phpqa.yml` or other way ? 

i need to integrate some rules for phpmetrics like bellow : 
```yaml
default:
    rules:
        cyclomaticComplexity: [ 10, 6, 2 ]
        maintainabilityIndex: [ 0, 75, 95 ]

    failure: average.maintainabilityIndex < 80 or average.bugs >= 1 or average.cyclomaticComplexity >= 4 or average.lcom >= 3
```
and so it will be awesome to have an aware  `.phpqa.yml`  like this : 

```yaml
phpcpd:
    minLines: 5
    minTokens: 70

phpmetrics:
    config: .phpmetrics.yml
```

thks in advance ;)
