### ISSUE TITLE
Add option to bundle jQuery and bootstrap

### ISSUE THREAD

**Issue by kanduvisla** [EdgedesignCZ/phpqa#95]
Our build server (Jenkins) has the security policy that it does not allow loading external resources in it's reports. This means that the jQuery and bootstrap JavaScript and CSS files in the template are blocked, rendering the report broken.

Would it be an idea to add a configuration flag that bundles these assets in the reports so that there are no external dependencies required?

**Comment by zdenekdrahos** [comment]
@kanduvisla: what do you think about assets definition in [.phpqa.yml](https://github.com/EdgedesignCZ/phpqa/blob/master/.phpqa.yml#L68)? 

```yml
report:
    assets:
        # default url -> absolute link <script>...
        bootstrap.js: https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js
        # local asset would be copied to `--buildDir` -> relative link in <script>...
        jquery.js: local-assets/jquery.min.js
```

**Comment by kanduvisla** [comment]
Perhaps it would be nicer to have a boolean flag that downloads it from the CDN during build. In that case you don't need to 'pollute' your repository with assets that are not directly project-related. For example:

```
report:
    assets:
        # false: templates will have links to CDN (default)
        # true: assets will be downloaded and bundled with build
        bundle_with_report: true
```
